### ISSUE TITLE
runtime: out of memory

### ISSUE THREAD

**Issue by antonipx** [antonipx/slackit#5]
2018/08/22 21:52:42 4.15.123.2:24219 Received file pxlog_uat108-14_2018-08-15_19-01-36.tgz (142086256) for channel astest
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x72c809, 0x16)
	/usr/local/go/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc4312f0000, 0x10190000, 0x0, 0x8e7b78)
	/usr/local/go/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x8cea20, 0x10190000, 0x1)
	/usr/local/go/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x8cea20, 0x80c7, 0x0)
	/usr/local/go/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0x8cea20, 0x80c7, 0x8e7b88, 0x202f)
	/usr/local/go/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0x8cea20, 0x80c7, 0xffffffffffff0101, 0x7ffca4795890)
	/usr/local/go/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0x8cea20, 0x80c7, 0x7ffca4010101, 0x430dc7)
	/usr/local/go/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0x1018e000, 0x7ffca4790101, 0x430f96)
	/usr/local/go/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1175

goroutine 6 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:363 fp=0xc4200f0f70 sp=0xc4200f0f68 pc=0x451de0
runtime.mallocgc(0x1018e000, 0x6aeae0, 0x1, 0xc4200f1048)
	/usr/local/go/src/runtime/malloc.go:720 +0x8a2 fp=0xc4200f1010 sp=0xc4200f0f70 pc=0x40ff92
runtime.makeslice(0x6aeae0, 0x1018e000, 0x1018e000, 0x8000, 0x8000, 0x0)
	/usr/local/go/src/runtime/slice.go:61 +0x77 fp=0xc4200f1040 sp=0xc4200f1010 pc=0x43e507
bytes.makeSlice(0x1018e000, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:230 +0x6d fp=0xc4200f1080 sp=0xc4200f1040 pc=0x4cf08d
bytes.(*Buffer).grow(0xc4205ab6c0, 0x8000, 0xc420810000)
	/usr/local/go/src/bytes/buffer.go:144 +0x151 fp=0xc4200f10d0 sp=0xc4200f1080 pc=0x4cea41
bytes.(*Buffer).Write(0xc4205ab6c0, 0xc420810000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:174 +0xd9 fp=0xc4200f1100 sp=0xc4200f10d0 pc=0x4ced19
mime/multipart.(*part).Write(0xc4206090e0, 0xc420810000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/usr/local/go/src/mime/multipart/writer.go:190 +0xc3 fp=0xc4200f1148 sp=0xc4200f1100 pc=0x5b8fd3
io.copyBuffer(0x762140, 0xc4206090e0, 0x7625a0, 0xc42000c158, 0xc420810000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:402 +0x240 fp=0xc4200f11b8 sp=0xc4200f1148 pc=0x46a890
io.Copy(0x762140, 0xc4206090e0, 0x7625a0, 0xc42000c158, 0x27, 0x762140, 0xc4206090e0)
	/usr/local/go/src/io/io.go:362 +0x5a fp=0xc4200f1218 sp=0xc4200f11b8 pc=0x46a51a
github.com/nlopes/slack.fileUploadReq(0x7652a0, 0xc420018028, 0xc4205e0bd0, 0x22, 0x72743e, 0x4, 0xc42001206e, 0x27, 0xc4200f14c8, 0x7625a0, ...)
	/home/as/src/src/github.com/nlopes/slack/misc.go:52 +0xd7 fp=0xc4200f1298 sp=0xc4200f1218 pc=0x6557e7
github.com/nlopes/slack.postWithMultipartResponse(0x7652a0, 0xc420018028, 0x7622e0, 0x8c8780, 0x7291fc, 0xc, 0xc42001206e, 0x27, 0x72743e, 0x4, ...)
	/home/as/src/src/github.com/nlopes/slack/misc.go:97 +0x106 fp=0xc4200f1338 sp=0xc4200f1298 pc=0x655fa6
github.com/nlopes/slack.postLocalWithMultipartResponse(0x7652a0, 0xc420018028, 0x7622e0, 0x8c8780, 0x7291fc, 0xc, 0xc420012050, 0x45, 0x72743e, 0x4, ...)
	/home/as/src/src/github.com/nlopes/slack/misc.go:93 +0x1ad fp=0xc4200f13e0 sp=0xc4200f1338 pc=0x655dfd
github.com/nlopes/slack.(*Client).UploadFileContext(0xc420100180, 0x7652a0, 0xc420018028, 0xc420012050, 0x45, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/as/src/src/github.com/nlopes/slack/files.go:247 +0x4e7 fp=0xc4200f1658 sp=0xc4200f13e0 pc=0x654a07
github.com/nlopes/slack.(*Client).UploadFile(0xc420100180, 0xc420012050, 0x45, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/as/src/src/github.com/nlopes/slack/files.go:213 +0x85 fp=0xc4200f1720 sp=0xc4200f1658 pc=0x6544d5
main.slackit(0x765020, 0xc4201621c0, 0xc420176000)
	/home/as/Code/slackit/slackit.go:103 +0xc38 fp=0xc4200f1cf0 sp=0xc4200f1720 pc=0x6768c8
net/http.HandlerFunc.ServeHTTP(0x73d290, 0x765020, 0xc4201621c0, 0xc420176000)
	/usr/local/go/src/net/http/server.go:1947 +0x44 fp=0xc4200f1d18 sp=0xc4200f1cf0 pc=0x6160d4
net/http.(*ServeMux).ServeHTTP(0xc42005aed0, 0x765020, 0xc4201621c0, 0xc420176000)
	/usr/local/go/src/net/http/server.go:2337 +0x130 fp=0xc4200f1d58 sp=0xc4200f1d18 pc=0x617d40
net/http.serverHandler.ServeHTTP(0xc42005cd00, 0x765020, 0xc4201621c0, 0xc420176000)
	/usr/local/go/src/net/http/server.go:2694 +0xbc fp=0xc4200f1d88 sp=0xc4200f1d58 pc=0x6187ec
net/http.(*conn).serve(0xc420068960, 0x765260, 0xc42004ab00)
	/usr/local/go/src/net/http/server.go:1830 +0x651 fp=0xc4200f1fc8 sp=0xc4200f1d88 pc=0x6152e1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4200f1fd0 sp=0xc4200f1fc8 pc=0x4547b1
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f65930bbf00, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200fc198, 0x72, 0xc42004a000, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4200fc198, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc4200fc180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:372 +0x1a8
net.(*netFD).accept(0xc4200fc180, 0x7f6593117000, 0x0, 0x73da50)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42000c048, 0xc4200f1d78, 0x410238, 0x30)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42000c048, 0x6fa1e0, 0xc42005b080, 0x6c0080)
	/usr/local/go/src/net/tcpsock.go:246 +0x49
net/http.tcpKeepAliveListener.Accept(0xc42000c048, 0xc420018028, 0x6c0080, 0x8bc7e0, 0x718200)
	/usr/local/go/src/net/http/server.go:3216 +0x2f
net/http.(*Server).Serve(0xc42005cdd0, 0x7651a0, 0xc42000c048, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2770 +0x1a5
net/http.(*Server).ListenAndServe(0xc42005cdd0, 0x2, 0x2)
	/usr/local/go/src/net/http/server.go:2711 +0xa9
main.main()
	/home/as/Code/slackit/slackit.go:186 +0x3c0

goroutine 5 [IO wait]:
internal/poll.runtime_pollWait(0x7f65930bbe30, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200fc218, 0x72, 0xc42004a000, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4200fc218, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc4200fc200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:372 +0x1a8
net.(*netFD).accept(0xc4200fc200, 0xc42004a0a0, 0x50, 0x6ec9a0)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42000c058, 0x73da50, 0xc420046cb0, 0xc420046cb0)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42000c058, 0x6bd140, 0x6bd140, 0xc420046ce0)
	/usr/local/go/src/net/tcpsock.go:246 +0x49
net/http.tcpKeepAliveListener.Accept(0xc42000c058, 0x432194, 0xc420046ce8, 0x4513d0, 0xc420046d28)
	/usr/local/go/src/net/http/server.go:3216 +0x2f
crypto/tls.(*listener).Accept(0xc4200d2360, 0x73d418, 0xc420068960, 0x765320, 0xc42005b1a0)
	/usr/local/go/src/crypto/tls/tls.go:52 +0x37
net/http.(*Server).Serve(0xc42005cd00, 0x764da0, 0xc4200d2360, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2770 +0x1a5
net/http.(*Server).ServeTLS(0xc42005cd00, 0x7651a0, 0xc42000c058, 0x0, 0x0, 0x0, 0x0, 0x0, 0x22)
	/usr/local/go/src/net/http/server.go:2839 +0x27b
net/http.(*Server).ListenAndServeTLS(0xc42005cd00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:3032 +0x11e
main.main.func2(0xc42005cd00)
	/home/as/Code/slackit/slackit.go:171 +0xb7
created by main.main
	/home/as/Code/slackit/slackit.go:169 +0x2fa

goroutine 11 [IO wait]:
internal/poll.runtime_pollWait(0x7f65930bbd60, 0x72, 0xc420029c10)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200fc298, 0x72, 0xffffffffffffff00, 0x762fe0, 0x8912d8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4200fc298, 0xc420178000, 0x8000, 0x8000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4200fc280, 0xc420178000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc4200fc280, 0xc420178000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42000c068, 0xc420178000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc42005b290, 0x7f65930bbfd0, 0xc42000c068, 0x5, 0xc42000c068, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:493 +0x96
crypto/tls.(*Conn).readRecord(0xc4200f8a80, 0x73da17, 0xc4200f8ba0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).Read(0xc4200f8a80, 0xc42005bcf1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1156 +0x100
net/http.(*connReader).backgroundRead(0xc42005bce0)
	/usr/local/go/src/net/http/server.go:668 +0x5a
created by net/http.(*connReader).startBackgroundRead
	/usr/local/go/src/net/http/server.go:664 +0xce

goroutine 19 [IO wait]:
internal/poll.runtime_pollWait(0x7f65930bbc90, 0x72, 0xc420047858)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200fca98, 0x72, 0xffffffffffffff00, 0x762fe0, 0x8912d8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4200fca98, 0xc420716000, 0x2000, 0x2000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4200fca80, 0xc420716000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc4200fca80, 0xc420716000, 0x2000, 0x2000, 0x8, 0x8, 0x1ff3)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42000c0b8, 0xc420716000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc42005bd10, 0x7f65930bbfd0, 0xc42000c0b8, 0x5, 0xc42000c0b8, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:493 +0x96
crypto/tls.(*Conn).readRecord(0xc4200ac000, 0x73da17, 0xc4200ac120, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).Read(0xc4200ac000, 0xc420711000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1156 +0x100
bufio.(*Reader).Read(0xc42049f8c0, 0xc4205bb618, 0x9, 0x9, 0xc420047c50, 0x467433, 0xc420047c60)
	/usr/local/go/src/bufio/bufio.go:216 +0x238
io.ReadAtLeast(0x761da0, 0xc42049f8c0, 0xc4205bb618, 0x9, 0x9, 0x9, 0xc4206c7301, 0xc420047d00, 0x60182b)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x761da0, 0xc42049f8c0, 0xc4205bb618, 0x9, 0x9, 0xc42000e070, 0xc420047d30, 0x60173d)
	/usr/local/go/src/io/io.go:327 +0x58
net/http.http2readFrameHeader(0xc4205bb618, 0x9, 0x9, 0x761da0, 0xc42049f8c0, 0x0, 0x0, 0xc4206f1290, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:1517 +0x7b
net/http.(*http2Framer).ReadFrame(0xc4205bb5e0, 0xc4206f1290, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:1775 +0xa4
net/http.(*http2clientConnReadLoop).run(0xc420047fb8, 0x73d460, 0xc420029fb8)
	/usr/local/go/src/net/http/h2_bundle.go:8028 +0x90
net/http.(*http2ClientConn).readLoop(0xc420523c00)
	/usr/local/go/src/net/http/h2_bundle.go:7956 +0x68
created by net/http.(*http2Transport).newClientConn
	/usr/local/go/src/net/http/h2_bundle.go:7143 +0x65c

**Comment by antonipx** [comment]
https://stackoverflow.com/questions/23234755/io-copy-cause-out-of-memory-in-golang
